# Generated by Django 5.1.5 on 2025-02-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adress',
            name='zip_code',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
